const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      Image: '/images/p1.jpg',
      price: 12000,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 27,
      description: 'high quality shirt',
    },
    {
      name: 'Addidas slim shirt',
      slug: 'Addidas-slim-shirt',
      category: 'Shirts',
      Image: '/images/p2.jpg',
      price: 6000,
      countInStock: 400,
      brand: 'Addidas',
      rating: 4.3,
      numReviews: 15,
      description: 'high quality shirt',
    },
    {
      name: 'Puma slim shirt',
      slug: 'Puma-slim-shirt',
      category: 'Shirts',
      Image: '/images/p3.jpg',
      price: 3200,
      countInStock: 100,
      brand: 'PUMA',
      rating: 4.1,
      numReviews: 27,
      description: 'high quality shirt',
    },
    {
      name: 'Levis slim shirt',
      slug: 'Levis-slim-shirt',
      category: 'Shirts',
      Image: '/images/p4.jpg',
      price: 4500,
      countInStock: 10,
      brand: 'Levis',
      rating: 4.6,
      numReviews: 207,
      description: 'high quality shirt',
    },
  ],
};

export default data;
